module.exports={
    entry: __dirname+'/app/main.js',
    output:{
        path:__dirname+'/public',
        filename:'bundle.js'
    },
    devtool:'eval-source-map',
    devServer:{
        contentBase:"./public",
        historyApiFallback:true,
        inline:true
    },
    module:{
        rules:[
            {
                test: /\.css$/,
                use:[
                    {
                        loader:'style-loader',
                    },{
                        loader:'css-loader'
                    }
                ]
            },
            {
                test: /\.js$/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['env','react']
                    }
                },
                exclude:/node_modules/
            },
            {
                test:/\.(png|jpg)$/,
                use:{
                    loader:'url-loader'
                }
            },
            {
                test:/\.svg$/,
                use:{
                    loader:'file-loader'
                }
            }
        ]
    }
}